defmodule Patchbay.Repo.Migrations.AddForum do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:forum_replies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :browser_session_id, :uuid, null: false
      add :verdict, :text, null: false
      add :note, :text
      add :owner_response, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :report_id, :uuid, null: false
    end

    create table(:forum_reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:forum_replies) do
      modify :report_id,
             references(:forum_reports,
               column: :id,
               name: "forum_replies_report_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:forum_replies, [:report_id])

    alter table(:forum_reports) do
      add :browser_session_id, :uuid, null: false
      add :arguments_sha256, :text, null: false
      add :handler_result, :map, null: false, default: %{}
      add :observed, :map, null: false, default: %{}
      add :verdict, :text, null: false
      add :failure_code, :text
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tool_id, :uuid, null: false
    end

    create table(:forum_sites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :origin, :text, null: false
      add :claimed_at, :utc_datetime_usec
      add :claim_kind, :text, null: false, default: "none"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:forum_sites, [:origin], name: "forum_sites_unique_origin_index")

    create table(:forum_tools, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:forum_reports) do
      modify :tool_id,
             references(:forum_tools,
               column: :id,
               name: "forum_reports_tool_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:forum_reports, [:tool_id])

    alter table(:forum_tools) do
      add :name, :text, null: false
      add :contract_sha256, :text, null: false
      add :title, :text
      add :description, :text

      add :first_seen_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :last_seen_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :site_id,
          references(:forum_sites,
            column: :id,
            name: "forum_tools_site_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:forum_tools, [:site_id, :name, :contract_sha256],
             name: "forum_tools_unique_contract_index"
           )
  end

  def down do
    drop constraint(:forum_tools, "forum_tools_site_id_fkey")

    drop_if_exists unique_index(:forum_tools, [:site_id, :name, :contract_sha256],
                     name: "forum_tools_unique_contract_index"
                   )

    alter table(:forum_tools) do
      remove :site_id
      remove :last_seen_at
      remove :first_seen_at
      remove :description
      remove :title
      remove :contract_sha256
      remove :name
    end

    drop_if_exists index(:forum_reports, [:tool_id])

    drop constraint(:forum_reports, "forum_reports_tool_id_fkey")

    alter table(:forum_reports) do
      modify :tool_id, :uuid
    end

    drop table(:forum_tools)

    drop_if_exists unique_index(:forum_sites, [:origin], name: "forum_sites_unique_origin_index")

    drop table(:forum_sites)

    alter table(:forum_reports) do
      remove :tool_id
      remove :inserted_at
      remove :note
      remove :failure_code
      remove :verdict
      remove :observed
      remove :handler_result
      remove :arguments_sha256
      remove :browser_session_id
    end

    drop_if_exists index(:forum_replies, [:report_id])

    drop constraint(:forum_replies, "forum_replies_report_id_fkey")

    alter table(:forum_replies) do
      modify :report_id, :uuid
    end

    drop table(:forum_reports)

    drop table(:forum_replies)
  end
end
