defmodule Patchbay.Repo.Migrations.OffersBidsHeldInCredits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:offer_placements, :offer_placements_settlement_conserves)

    drop_if_exists constraint(:offer_placements, :offer_placements_tx_hash_format)

    alter table(:offer_placements) do
      remove :settle_tx_hash
    end

    create constraint(:offer_placements, :offer_placements_settlement_conserves,
             check: """
               CASE status
               WHEN 'active' THEN ended_at IS NULL AND returned_minor IS NULL AND consumed_minor IS NULL AND forfeited_minor IS NULL
               ELSE ended_at IS NOT NULL
                 AND returned_minor >= 0 AND consumed_minor >= 0 AND forfeited_minor >= 0
                 AND returned_minor + consumed_minor + forfeited_minor = amount_minor
                 AND (status <> 'expired' OR (returned_minor = 0 AND forfeited_minor = 0))
                 AND (status <> 'bought_out' OR forfeited_minor = 0)
                 AND (status <> 'removed_for_policy' OR returned_minor = 0)
             END

             """
           )

    alter table(:offer_bids) do
      remove :release_tx_hash
    end

    drop_if_exists constraint(:offer_bids, :offer_bids_funding_shape)

    alter table(:offer_bids) do
      remove :funding
    end

    drop_if_exists constraint(:offer_bids, :offer_bids_payer_address_format)

    alter table(:offer_bids) do
      remove :payer_address
    end

    drop_if_exists constraint(:offer_bids, :offer_bids_tx_hash_format)

    alter table(:offer_bids) do
      remove :commit_tx_hash
    end
  end

  def down do
    alter table(:offer_bids) do
      add :payer_address, :text, null: false
      add :funding, :text, null: false, default: "awaiting_funds"
      add :commit_tx_hash, :text
      add :release_tx_hash, :text
    end

    create constraint(:offer_bids, :offer_bids_payer_address_format,
             check: """
               payer_address ~ '^0x[0-9a-f]{40}$'
             """
           )

    create constraint(:offer_bids, :offer_bids_funding_shape,
             check: """
               (funding = 'funded') = (commit_tx_hash IS NOT NULL)
               AND (status NOT IN ('leading', 'placed') OR funding = 'funded')
               AND (release_tx_hash IS NULL OR (status = 'returned' AND funding = 'funded'))

             """
           )

    create constraint(:offer_bids, :offer_bids_tx_hash_format,
             check: """
               (commit_tx_hash IS NULL OR commit_tx_hash ~ '^0x[0-9a-f]{64}$') AND (release_tx_hash IS NULL OR release_tx_hash ~ '^0x[0-9a-f]{64}$')
             """
           )

    drop_if_exists constraint(:offer_placements, :offer_placements_settlement_conserves)

    alter table(:offer_placements) do
      add :settle_tx_hash, :text
    end

    create constraint(:offer_placements, :offer_placements_tx_hash_format,
             check: """
               settle_tx_hash IS NULL OR settle_tx_hash ~ '^0x[0-9a-f]{64}$'
             """
           )

    create constraint(:offer_placements, :offer_placements_settlement_conserves,
             check: """
               CASE status
               WHEN 'active' THEN ended_at IS NULL AND returned_minor IS NULL AND consumed_minor IS NULL AND forfeited_minor IS NULL AND settle_tx_hash IS NULL
               ELSE ended_at IS NOT NULL
                 AND returned_minor >= 0 AND consumed_minor >= 0 AND forfeited_minor >= 0
                 AND returned_minor + consumed_minor + forfeited_minor = amount_minor
                 AND (status <> 'expired' OR (returned_minor = 0 AND forfeited_minor = 0))
                 AND (status <> 'bought_out' OR forfeited_minor = 0)
                 AND (status <> 'removed_for_policy' OR returned_minor = 0)
             END

             """
           )
  end
end
