defmodule Patchbay.Repo.Migrations.OfferReviewDecisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:offer_moderation_actions) do
      add :review_id,
          references(:offer_reviews,
            column: :id,
            name: "offer_moderation_actions_review_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create index(:offer_moderation_actions, [:review_id])
  end

  def down do
    drop_if_exists index(:offer_moderation_actions, [:review_id])

    drop constraint(:offer_moderation_actions, "offer_moderation_actions_review_id_fkey")

    alter table(:offer_moderation_actions) do
      remove :review_id
    end
  end
end
