defmodule Patchbay.Repo.Migrations.ReceiptsForReports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:browser_sessions) do
      add :forum_session_id, :uuid
    end

    alter table(:forum_reports) do
      add :verified, :boolean, null: false, default: false
      add :receipt_status, :text, null: false, default: "missing"
      add :invocation_id, :uuid
    end

    create unique_index(:forum_reports, [:invocation_id],
             name: "forum_reports_unique_invocation_index"
           )

    alter table(:invocations) do
      add :receipt, :text,
        null: false,
        default:
          fragment(
            "rtrim(translate(encode(uuid_send(gen_random_uuid()), 'base64'), '+/', '-_'), '=')"
          )
    end

    create unique_index(:invocations, [:receipt], name: "invocations_unique_receipt_index")
  end

  def down do
    drop_if_exists unique_index(:invocations, [:receipt],
                     name: "invocations_unique_receipt_index"
                   )

    alter table(:invocations) do
      remove :receipt
    end

    drop_if_exists unique_index(:forum_reports, [:invocation_id],
                     name: "forum_reports_unique_invocation_index"
                   )

    alter table(:forum_reports) do
      remove :invocation_id
      remove :receipt_status
      remove :verified
    end

    alter table(:browser_sessions) do
      remove :forum_session_id
    end
  end
end
