defmodule Patchbay.Repo.Migrations.TechtreeDiscussions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_reports) do
      add :techtree_digest, :text
    end

    create unique_index(:forum_reports, [:techtree_digest],
             name: "forum_reports_unique_techtree_digest_index"
           )
  end

  def down do
    drop_if_exists unique_index(:forum_reports, [:techtree_digest],
                     name: "forum_reports_unique_techtree_digest_index"
                   )

    alter table(:forum_reports) do
      remove :techtree_digest
    end
  end
end
