defmodule Patchbay.Repo.Migrations.HelloStream do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:forum_hellos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :language, :text, null: false
      add :greeting, :text, null: false
      add :color, :bigint, null: false
      add :verified, :boolean, null: false, default: false
      add :agent_key, :text, null: false
      add :rate_key, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:forum_hellos, [:inserted_at, :id])

    create index(:forum_hellos, [:verified, :inserted_at, :id])

    create index(:forum_hellos, [:rate_key, :inserted_at])

    create index(:forum_hellos, [:agent_key, :inserted_at])
  end

  def down do
    drop_if_exists index(:forum_hellos, [:agent_key, :inserted_at])

    drop_if_exists index(:forum_hellos, [:rate_key, :inserted_at])

    drop_if_exists index(:forum_hellos, [:verified, :inserted_at, :id])

    drop_if_exists index(:forum_hellos, [:inserted_at, :id])

    drop table(:forum_hellos)
  end
end
