defmodule Patchbay.Repo.Migrations.AssistRunsPayFromSharedPayments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:assist_runs, "assist_runs_payment_intent_id_fkey")

    alter table(:assist_runs) do
      modify :payment_intent_id, :uuid
    end
  end

  def down do
    alter table(:assist_runs) do
      modify :payment_intent_id,
             references(:payment_intents,
               column: :id,
               name: "assist_runs_payment_intent_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
