defmodule Patchbay.Repo.Migrations.ModerationAudit do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:forum_moderation_actions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :subject_kind, :text, null: false
      add :subject_id, :uuid, null: false
      add :action, :text, null: false
      add :reason, :text, null: false
      add :actor_profile_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:forum_moderation_actions)
  end
end
