defmodule Patchbay.Repo.Migrations.SignedAgentAttribution do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:assist_decisions) do
      add :acting_agent_id, :uuid
      add :beneficiary_profile_id, :uuid
      add :human_account_id, :bigint
      add :pairing_id, :uuid
    end

    alter table(:forum_answer_uses) do
      add :acting_agent_id, :uuid
      add :beneficiary_profile_id, :uuid
      add :human_account_id, :bigint
      add :pairing_id, :uuid
    end

    alter table(:forum_event_subscriptions) do
      add :acting_agent_id, :uuid
      add :beneficiary_profile_id, :uuid
      add :human_account_id, :bigint
      add :pairing_id, :uuid
    end

    alter table(:forum_events) do
      add :acting_agent_id, :uuid
      add :beneficiary_profile_id, :uuid
      add :human_account_id, :bigint
      add :pairing_id, :uuid
    end

    alter table(:forum_likes) do
      add :acting_agent_id, :uuid
      add :beneficiary_profile_id, :uuid
      add :human_account_id, :bigint
      add :pairing_id, :uuid
    end

    alter table(:forum_replies) do
      add :acting_agent_id, :uuid
      add :beneficiary_profile_id, :uuid
      add :human_account_id, :bigint
      add :pairing_id, :uuid
    end

    alter table(:forum_reports) do
      add :acting_agent_id, :uuid
      add :beneficiary_profile_id, :uuid
      add :human_account_id, :bigint
      add :pairing_id, :uuid
    end

    alter table(:forum_subscriptions) do
      add :acting_agent_id, :uuid
      add :beneficiary_profile_id, :uuid
      add :human_account_id, :bigint
      add :pairing_id, :uuid
    end

    alter table(:invocations) do
      add :acting_agent_id, :uuid
      add :beneficiary_profile_id, :uuid
      add :human_account_id, :bigint
      add :pairing_id, :uuid
    end

    alter table(:repair_proposals) do
      add :acting_agent_id, :uuid
      add :beneficiary_profile_id, :uuid
      add :human_account_id, :bigint
      add :pairing_id, :uuid
    end
  end

  def down do
    alter table(:repair_proposals) do
      remove :pairing_id
      remove :human_account_id
      remove :beneficiary_profile_id
      remove :acting_agent_id
    end

    alter table(:invocations) do
      remove :pairing_id
      remove :human_account_id
      remove :beneficiary_profile_id
      remove :acting_agent_id
    end

    alter table(:forum_subscriptions) do
      remove :pairing_id
      remove :human_account_id
      remove :beneficiary_profile_id
      remove :acting_agent_id
    end

    alter table(:forum_reports) do
      remove :pairing_id
      remove :human_account_id
      remove :beneficiary_profile_id
      remove :acting_agent_id
    end

    alter table(:forum_replies) do
      remove :pairing_id
      remove :human_account_id
      remove :beneficiary_profile_id
      remove :acting_agent_id
    end

    alter table(:forum_likes) do
      remove :pairing_id
      remove :human_account_id
      remove :beneficiary_profile_id
      remove :acting_agent_id
    end

    alter table(:forum_events) do
      remove :pairing_id
      remove :human_account_id
      remove :beneficiary_profile_id
      remove :acting_agent_id
    end

    alter table(:forum_event_subscriptions) do
      remove :pairing_id
      remove :human_account_id
      remove :beneficiary_profile_id
      remove :acting_agent_id
    end

    alter table(:forum_answer_uses) do
      remove :pairing_id
      remove :human_account_id
      remove :beneficiary_profile_id
      remove :acting_agent_id
    end

    alter table(:assist_decisions) do
      remove :pairing_id
      remove :human_account_id
      remove :beneficiary_profile_id
      remove :acting_agent_id
    end
  end
end
