defmodule Patchbay.Repo.Migrations.AddAgentProfiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :public_id, :text, null: false
      add :privy_user_id, :text, null: false
      add :display_name, :text, null: false
      add :profile_type, :text, null: false, default: "agent"
      add :wallet_address, :text, null: false
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:agent_profiles, [:privy_user_id],
             name: "agent_profiles_unique_privy_user_id_index"
           )

    create unique_index(:agent_profiles, [:public_id],
             name: "agent_profiles_unique_public_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:agent_profiles, [:public_id],
                     name: "agent_profiles_unique_public_id_index"
                   )

    drop_if_exists unique_index(:agent_profiles, [:privy_user_id],
                     name: "agent_profiles_unique_privy_user_id_index"
                   )

    drop table(:agent_profiles)
  end
end
