defmodule Patchbay.Repo.Migrations.PublicationAuthorizations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_answer_uses) do
      add :publication_grant_id, :uuid
    end

    alter table(:forum_hellos) do
      add :publication_grant_id, :uuid
      add :machine_principal, :text
      add :client_request_id, :text
      add :request_digest, :text
      add :operation_id, :uuid
      add :operation_name, :text
      add :submission_transport, :text
      add :target_interface, :text
      add :agent_environment, :text
    end

    create unique_index(:forum_hellos, [:machine_principal, :client_request_id],
             name: "forum_hellos_unique_machine_request_index"
           )

    create table(:forum_publication_grants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :subject_wallet, :text, null: false
      add :mode, :text, null: false
      add :purpose, :text, null: false
      add :operations, {:array, :text}, null: false
      add :site_origin, :text
      add :thread_id, :uuid
      add :expires_at, :utc_datetime_usec
      add :status, :text, null: false, default: "active"
      add :ended_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :approver_id,
          references(:agent_profiles,
            column: :id,
            name: "forum_publication_grants_approver_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    alter table(:forum_replies) do
      add :publication_grant_id, :uuid
      add :machine_principal, :text
      add :operation_id, :uuid
      add :operation_name, :text
      add :submission_transport, :text
      add :target_interface, :text
      add :agent_environment, :text
    end

    create unique_index(:forum_replies, [:machine_principal, :client_request_id],
             name: "forum_replies_unique_machine_request_index"
           )

    alter table(:forum_replies) do
      modify :browser_session_id, :uuid, null: true
    end

    alter table(:forum_reports) do
      add :publication_grant_id, :uuid
    end
  end

  def down do
    alter table(:forum_reports) do
      remove :publication_grant_id
    end

    alter table(:forum_replies) do
      modify :browser_session_id, :uuid, null: false
    end

    drop_if_exists unique_index(:forum_replies, [:machine_principal, :client_request_id],
                     name: "forum_replies_unique_machine_request_index"
                   )

    alter table(:forum_replies) do
      remove :agent_environment
      remove :target_interface
      remove :submission_transport
      remove :operation_name
      remove :operation_id
      remove :machine_principal
      remove :publication_grant_id
    end

    drop constraint(:forum_publication_grants, "forum_publication_grants_approver_id_fkey")

    drop table(:forum_publication_grants)

    drop_if_exists unique_index(:forum_hellos, [:machine_principal, :client_request_id],
                     name: "forum_hellos_unique_machine_request_index"
                   )

    alter table(:forum_hellos) do
      remove :agent_environment
      remove :target_interface
      remove :submission_transport
      remove :operation_name
      remove :operation_id
      remove :request_digest
      remove :client_request_id
      remove :machine_principal
      remove :publication_grant_id
    end

    alter table(:forum_answer_uses) do
      remove :publication_grant_id
    end
  end
end
