defmodule Patchbay.Repo.Migrations.AddAssistFeeDeposit do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:assist_runs) do
      add :deposit_status, :text, null: false, default: "pending"
      add :deposit_tx_hash, :text
    end
  end

  def down do
    alter table(:assist_runs) do
      remove :deposit_tx_hash
      remove :deposit_status
    end
  end
end
