defmodule Patchbay.Repo.Migrations.FixPatchbayBootstrap do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:browser_sessions, [:client_instance_id],
                     name: "browser_sessions_unique_client_instance_id_index"
                   )

    create unique_index(:browser_sessions, [:room_id, :client_instance_id],
             name: "browser_sessions_unique_client_instance_id_per_room_index"
           )
  end

  def down do
    drop_if_exists unique_index(:browser_sessions, [:room_id, :client_instance_id],
                     name: "browser_sessions_unique_client_instance_id_per_room_index"
                   )

    create unique_index(:browser_sessions, [:client_instance_id],
             name: "browser_sessions_unique_client_instance_id_index"
           )
  end
end
