defmodule Patchbay.Repo.Migrations.AddOfferReports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:offer_reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reporter, :text, null: false
      add :surface, :text, null: false
      add :reason, :text, null: false
      add :note, :text
      add :status, :text, null: false, default: "open"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :placement_id,
          references(:offer_placements,
            column: :id,
            name: "offer_reports_placement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:offer_reports, [:reporter, :placement_id],
             name: "offer_reports_once_per_reporter_index"
           )

    alter table(:offer_reports) do
      add :version_id,
          references(:offer_creative_versions,
            column: :id,
            name: "offer_reports_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :delivery_id,
          references(:offer_deliveries,
            column: :id,
            name: "offer_reports_delivery_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create constraint(:offer_reports, :offer_reports_note_size,
             check: """
               char_length(note) <= 2000 AND octet_length(note) <= 8192
             """
           )

    create index(:offer_reports, [:status, :inserted_at])

    create index(:offer_reports, [:placement_id, :inserted_at])

    create index(:offer_reports, [:version_id])
  end

  def down do
    drop_if_exists index(:offer_reports, [:version_id])

    drop_if_exists index(:offer_reports, [:placement_id, :inserted_at])

    drop_if_exists index(:offer_reports, [:status, :inserted_at])

    drop_if_exists constraint(:offer_reports, :offer_reports_note_size)

    drop constraint(:offer_reports, "offer_reports_delivery_id_fkey")

    drop constraint(:offer_reports, "offer_reports_version_id_fkey")

    drop constraint(:offer_reports, "offer_reports_placement_id_fkey")

    alter table(:offer_reports) do
      remove :delivery_id
      remove :version_id
    end

    drop_if_exists unique_index(:offer_reports, [:reporter, :placement_id],
                     name: "offer_reports_once_per_reporter_index"
                   )

    drop table(:offer_reports)
  end
end
