defmodule Patchbay.Repo.Migrations.RecordModelCalls do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:assist_decisions, [:choice, :result])

    create index(:assist_decisions, [:assist_run_id])

    create table(:assist_model_calls, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :purpose, :text, null: false
      add :model, :text, null: false
      add :visitor_key, :text
      add :outcome, :text, null: false, default: "asked"
      add :prompt_tokens, :bigint
      add :completion_tokens, :bigint
      add :cost_usd, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :assist_run_id,
          references(:assist_runs,
            column: :id,
            name: "assist_model_calls_assist_run_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )
    end

    create index(:assist_model_calls, [:inserted_at])

    create index(:assist_model_calls, [:purpose, :visitor_key, :inserted_at])

    create index(:assist_model_calls, [:assist_run_id])
  end

  def down do
    drop_if_exists index(:assist_model_calls, [:assist_run_id])

    drop_if_exists index(:assist_model_calls, [:purpose, :visitor_key, :inserted_at])

    drop_if_exists index(:assist_model_calls, [:inserted_at])

    drop constraint(:assist_model_calls, "assist_model_calls_assist_run_id_fkey")

    drop table(:assist_model_calls)

    drop_if_exists index(:assist_decisions, [:assist_run_id])

    drop_if_exists index(:assist_decisions, [:choice, :result])
  end
end
