defmodule Patchbay.Repo.Migrations.McpEventSubscriptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:forum_event_subscriptions, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :owner_id, :text, null: false
      add :name, :text, null: false
      add :arguments, :map, null: false
      add :url, :text, null: false
      add :secret_ciphertext, :text, null: false
      add :previous_secret_ciphertext, :text
      add :secret_rotation_expires_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec, null: false
      add :active, :boolean, null: false, default: true
      add :verified_at, :utc_datetime_usec, null: false
      add :delivered_seq, :bigint, null: false, default: 0
      add :pending_seq, :bigint
      add :attempt, :bigint, null: false, default: 0
      add :lease_token, :text
      add :lease_expires_at, :utc_datetime_usec
      add :next_attempt_at, :utc_datetime_usec
      add :last_error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:forum_event_subscriptions)
  end
end
