defmodule Patchbay.Repo.Migrations.AddOfferDeliveries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:offer_deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :surface, :text, null: false
      add :operation, :text, null: false
      add :selected_at, :utc_datetime_usec, null: false
      add :general_opportunities, {:array, :bigint}, null: false, default: []

      add :site_id,
          references(:forum_sites,
            column: :id,
            name: "offer_deliveries_site_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :report_id,
          references(:forum_reports,
            column: :id,
            name: "offer_deliveries_report_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :reply_id,
          references(:forum_replies,
            column: :id,
            name: "offer_deliveries_reply_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create unique_index(:offer_deliveries, [:report_id],
             name: "offer_deliveries_one_per_post_index",
             where: "(operation <> 'reply')"
           )

    create unique_index(:offer_deliveries, [:reply_id],
             name: "offer_deliveries_one_per_reply_index",
             where: "(operation = 'reply')"
           )

    create constraint(:offer_deliveries, :offer_deliveries_operation_shape,
             check: """
               (operation = 'reply') = (reply_id IS NOT NULL)
             """
           )

    create index(:offer_deliveries, [:site_id, :selected_at])

    create index(:offer_deliveries, [:selected_at])

    create table(:offer_delivery_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false
      add :scope, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :delivery_id,
          references(:offer_deliveries,
            column: :id,
            name: "offer_delivery_items_delivery_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:offer_delivery_items, [:delivery_id, :position],
             name: "offer_delivery_items_one_per_position_index"
           )

    alter table(:offer_delivery_items) do
      add :placement_id,
          references(:offer_placements,
            column: :id,
            name: "offer_delivery_items_placement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :version_id,
          references(:offer_creative_versions,
            column: :id,
            name: "offer_delivery_items_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create constraint(:offer_delivery_items, :offer_delivery_items_position_range,
             check: """
               position BETWEEN 1 AND 3
             """
           )

    create index(:offer_delivery_items, [:placement_id, :inserted_at])
  end

  def down do
    drop_if_exists index(:offer_delivery_items, [:placement_id, :inserted_at])

    drop_if_exists constraint(:offer_delivery_items, :offer_delivery_items_position_range)

    drop constraint(:offer_delivery_items, "offer_delivery_items_version_id_fkey")

    drop constraint(:offer_delivery_items, "offer_delivery_items_placement_id_fkey")

    drop constraint(:offer_delivery_items, "offer_delivery_items_delivery_id_fkey")

    alter table(:offer_delivery_items) do
      remove :version_id
      remove :placement_id
    end

    drop_if_exists unique_index(:offer_delivery_items, [:delivery_id, :position],
                     name: "offer_delivery_items_one_per_position_index"
                   )

    drop table(:offer_delivery_items)

    drop_if_exists index(:offer_deliveries, [:selected_at])

    drop_if_exists index(:offer_deliveries, [:site_id, :selected_at])

    drop_if_exists constraint(:offer_deliveries, :offer_deliveries_operation_shape)

    drop constraint(:offer_deliveries, "offer_deliveries_reply_id_fkey")

    drop constraint(:offer_deliveries, "offer_deliveries_report_id_fkey")

    drop constraint(:offer_deliveries, "offer_deliveries_site_id_fkey")

    drop_if_exists unique_index(:offer_deliveries, [:reply_id],
                     name: "offer_deliveries_one_per_reply_index"
                   )

    drop_if_exists unique_index(:offer_deliveries, [:report_id],
                     name: "offer_deliveries_one_per_post_index"
                   )

    drop table(:offer_deliveries)
  end
end
