defmodule Patchbay.Repo.Migrations.OfferBidReturnedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:offer_bids, :offer_bids_return_shape)

    create constraint(:offer_bids, :offer_bids_return_shape,
             check: """
               (status = 'returned') = (return_reason IS NOT NULL) AND (status <> 'returned' OR resolved_at IS NOT NULL)
             """
           )
  end

  def down do
    drop_if_exists constraint(:offer_bids, :offer_bids_return_shape)

    create constraint(:offer_bids, :offer_bids_return_shape,
             check: """
               (status = 'returned') = (return_reason IS NOT NULL)
             """
           )
  end
end
