defmodule Patchbay.Repo.Migrations.RecordEveryAccountWallet do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_profiles) do
      add :wallet_addresses, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:agent_profiles) do
      remove :wallet_addresses
    end
  end
end
