defmodule Patchbay.Repo.Migrations.GeneralThreads do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_replies) do
      add :reply_kind, :text
      add :body_markdown, :text
      add :visibility, :text, null: false, default: "published"
      modify :verdict, :text, null: true
    end

    alter table(:forum_reports) do
      add :thread_kind, :text, null: false, default: "failure_report"
      add :title, :text
      add :body_markdown, :text
      add :subject_tool_name, :text
      add :topic_tags, {:array, :text}, null: false, default: []
      add :discussion_state, :text, null: false, default: "open"
      add :visibility, :text, null: false, default: "published"
      add :content_version, :bigint, null: false, default: 1
      add :demo_fixture, :boolean, null: false, default: false

      add :last_activity_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :site_id,
          references(:forum_sites,
            column: :id,
            name: "forum_reports_site_id_fkey",
            type: :uuid
          )

      add :duplicate_of_id,
          references(:forum_reports,
            column: :id,
            name: "forum_reports_duplicate_of_id_fkey",
            type: :uuid
          )

      add :solution_reply_id,
          references(:forum_replies,
            column: :id,
            name: "forum_reports_solution_reply_id_fkey",
            type: :uuid
          )

      modify :arguments_sha256, :text, null: true
      modify :handler_result, :map, null: true, default: nil
      modify :observed, :map, null: true, default: nil
      modify :verdict, :text, null: true
      modify :tool_id, :uuid, null: true
    end

    # Existing reports named their site through their tool; the backfill is
    # complete because every one of them has a tool. Then the column becomes
    # required, and activity starts where the record was first written.
    schema = prefix() || "public"

    execute("""
    UPDATE #{schema}.forum_reports r
    SET site_id = t.site_id
    FROM #{schema}.forum_tools t
    WHERE r.tool_id = t.id
    """)

    execute("""
    UPDATE #{schema}.forum_reports SET last_activity_at = inserted_at
    """)

    alter table(:forum_reports) do
      modify :site_id, :uuid, null: false
    end

    create index(:forum_reports, [:site_id])
  end

  def down do
    drop_if_exists index(:forum_reports, [:site_id])

    drop constraint(:forum_reports, "forum_reports_solution_reply_id_fkey")

    drop constraint(:forum_reports, "forum_reports_duplicate_of_id_fkey")

    drop constraint(:forum_reports, "forum_reports_site_id_fkey")

    alter table(:forum_reports) do
      modify :tool_id, :uuid, null: false
      modify :verdict, :text, null: false
      modify :observed, :map, null: false, default: %{}
      modify :handler_result, :map, null: false, default: %{}
      modify :arguments_sha256, :text, null: false
      remove :solution_reply_id
      remove :duplicate_of_id
      remove :site_id
      remove :last_activity_at
      remove :demo_fixture
      remove :content_version
      remove :visibility
      remove :discussion_state
      remove :topic_tags
      remove :subject_tool_name
      remove :body_markdown
      remove :title
      remove :thread_kind
    end

    alter table(:forum_replies) do
      modify :verdict, :text, null: false
      remove :visibility
      remove :body_markdown
      remove :reply_kind
    end
  end
end
