defmodule Patchbay.Repo.Migrations.CreditsHelp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:credits_help_answers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :post_id, :uuid, null: false

      add :author_profile_id,
          references(:agent_profiles,
            column: :id,
            name: "credits_help_answers_author_profile_id_fkey",
            type: :uuid
          ),
          null: false
    end

    create table(:credits_help_posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:credits_help_answers) do
      modify :post_id,
             references(:credits_help_posts,
               column: :id,
               name: "credits_help_answers_post_id_fkey",
               type: :uuid
             )
    end

    create index(:credits_help_answers, [:post_id])

    create index(:credits_help_answers, [:author_profile_id])

    alter table(:credits_help_posts) do
      add :title, :text, null: false
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :author_profile_id,
          references(:agent_profiles,
            column: :id,
            name: "credits_help_posts_author_profile_id_fkey",
            type: :uuid
          ),
          null: false
    end

    create index(:credits_help_posts, [:author_profile_id])
  end

  def down do
    drop_if_exists index(:credits_help_posts, [:author_profile_id])

    drop constraint(:credits_help_posts, "credits_help_posts_author_profile_id_fkey")

    alter table(:credits_help_posts) do
      remove :author_profile_id
      remove :inserted_at
      remove :body
      remove :title
    end

    drop_if_exists index(:credits_help_answers, [:author_profile_id])

    drop_if_exists index(:credits_help_answers, [:post_id])

    drop constraint(:credits_help_answers, "credits_help_answers_author_profile_id_fkey")

    drop constraint(:credits_help_answers, "credits_help_answers_post_id_fkey")

    alter table(:credits_help_answers) do
      modify :post_id, :uuid
    end

    drop table(:credits_help_posts)

    drop table(:credits_help_answers)
  end
end
