defmodule Patchbay.Repo.Migrations.BountyRefundWindow do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_reports) do
      add :escrow_funded_at, :utc_datetime_usec
      add :refund_requested_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:forum_reports) do
      remove :refund_requested_at
      remove :escrow_funded_at
    end
  end
end
