defmodule Patchbay.Repo.Migrations.EventDeliveryOnOban do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_event_subscriptions) do
      remove :pending_seq
      remove :attempt
      remove :lease_token
      remove :lease_expires_at
      remove :next_attempt_at
    end
  end

  def down do
    alter table(:forum_event_subscriptions) do
      add :next_attempt_at, :utc_datetime_usec
      add :lease_expires_at, :utc_datetime_usec
      add :lease_token, :text
      add :attempt, :bigint, null: false, default: 0
      add :pending_seq, :bigint
    end
  end
end
