defmodule Patchbay.Repo.Migrations.AddAssistRunTimes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:assist_runs) do
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:assist_runs) do
      remove :finished_at
      remove :started_at
    end
  end
end
