defmodule Patchbay.Repo.Migrations.JevKnownFixes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:assist_decisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :site, :text, null: false
      add :goal, :text
      add :error, :text
      add :asked_from, :text, null: false
      add :visitor_key, :text
      add :choice, :text, null: false
      add :confidence, :float, null: false
      add :model, :text, null: false
      add :result, :text
      add :reported_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :assist_run_id,
          references(:assist_runs,
            column: :id,
            name: "assist_decisions_assist_run_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )
    end

    alter table(:assist_runs) do
      add :error, :text
    end
  end

  def down do
    alter table(:assist_runs) do
      remove :error
    end

    drop constraint(:assist_decisions, "assist_decisions_assist_run_id_fkey")

    drop table(:assist_decisions)
  end
end
