defmodule Patchbay.Repo.Migrations.PushEscrowRevenue do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_reports) do
      add :escrow_revenue_pushed_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:forum_reports) do
      remove :escrow_revenue_pushed_at
    end
  end
end
