defmodule Patchbay.Repo.Migrations.PostsIndexedByAuthor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:forum_replies, [:author_profile_id])

    create index(:forum_reports, [:author_profile_id])
  end

  def down do
    drop_if_exists index(:forum_reports, [:author_profile_id])

    drop_if_exists index(:forum_replies, [:author_profile_id])
  end
end
