defmodule Patchbay.Repo.Migrations.CheckGate2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:forum_answer_uses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :outcome, :text, null: false
      add :task_token, :text, null: false
      add :note, :text
      add :same_author, :boolean, null: false, default: false
      add :applicable_tool_version, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :principal, :text, null: false

      add :reply_id,
          references(:forum_replies,
            column: :id,
            name: "forum_answer_uses_reply_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:forum_answer_uses, [:reply_id, :principal, :task_token],
             name: "forum_answer_uses_principal_task_index"
           )

    create table(:forum_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :thread_id, :uuid, null: false
      add :site_id, :uuid, null: false
      add :tool_id, :uuid
      add :actor_principal, :text
      add :fanned_out_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:forum_notifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :recipient, :text, null: false
      add :acknowledged_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:forum_events,
            column: :id,
            name: "forum_notifications_event_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:forum_notifications, [:event_id, :recipient],
             name: "forum_notifications_event_recipient_index"
           )

    create table(:forum_solution_cards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :problem_summary, :text, null: false
      add :applicability, :text
      add :proposed_steps, :text, null: false
      add :caveats, :text
      add :source_digest, :text, null: false
      add :source_author_profile_id, :uuid
      add :status, :text, null: false, default: "published"
      add :reviewed_by_profile_id, :uuid
      add :reviewed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :thread_id,
          references(:forum_reports,
            column: :id,
            name: "forum_solution_cards_thread_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :source_reply_id,
          references(:forum_replies,
            column: :id,
            name: "forum_solution_cards_source_reply_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:forum_subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :principal, :text, null: false
      add :scope_kind, :text, null: false
      add :scope_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:forum_subscriptions, [:principal, :scope_kind, :scope_id],
             name: "forum_subscriptions_principal_scope_index"
           )
  end

  def down do
    drop_if_exists unique_index(:forum_subscriptions, [:principal, :scope_kind, :scope_id],
                     name: "forum_subscriptions_principal_scope_index"
                   )

    drop table(:forum_subscriptions)

    drop constraint(:forum_solution_cards, "forum_solution_cards_source_reply_id_fkey")

    drop constraint(:forum_solution_cards, "forum_solution_cards_thread_id_fkey")

    drop table(:forum_solution_cards)

    drop constraint(:forum_notifications, "forum_notifications_event_id_fkey")

    drop_if_exists unique_index(:forum_notifications, [:event_id, :recipient],
                     name: "forum_notifications_event_recipient_index"
                   )

    drop table(:forum_notifications)

    drop table(:forum_events)

    drop constraint(:forum_answer_uses, "forum_answer_uses_reply_id_fkey")

    drop_if_exists unique_index(:forum_answer_uses, [:reply_id, :principal, :task_token],
                     name: "forum_answer_uses_principal_task_index"
                   )

    drop table(:forum_answer_uses)
  end
end
