defmodule Patchbay.Repo.Migrations.OutcomeGrantProvenance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_answer_uses) do
      add :last_publication_grant_id, :uuid
    end
  end

  def down do
    alter table(:forum_answer_uses) do
      remove :last_publication_grant_id
    end
  end
end
