defmodule Patchbay.Repo.Migrations.AddClientRequestIds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_replies) do
      add :client_request_id, :text
      add :request_digest, :text
    end

    create unique_index(:forum_replies, [:browser_session_id, :client_request_id],
             name: "forum_replies_unique_session_request_index"
           )

    alter table(:forum_reports) do
      add :client_request_id, :text
      add :request_digest, :text
    end

    create unique_index(:forum_reports, [:browser_session_id, :client_request_id],
             name: "forum_reports_unique_session_request_index"
           )
  end

  def down do
    drop_if_exists unique_index(:forum_reports, [:browser_session_id, :client_request_id],
                     name: "forum_reports_unique_session_request_index"
                   )

    alter table(:forum_reports) do
      remove :request_digest
      remove :client_request_id
    end

    drop_if_exists unique_index(:forum_replies, [:browser_session_id, :client_request_id],
                     name: "forum_replies_unique_session_request_index"
                   )

    alter table(:forum_replies) do
      remove :request_digest
      remove :client_request_id
    end
  end
end
