defmodule Patchbay.Repo.Migrations.GiveUpOnJevReadings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_reports) do
      add :jev_gave_up_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:forum_reports) do
      remove :jev_gave_up_at
    end
  end
end
