defmodule Patchbay.Repo.Migrations.EndedPlacementsRecordTheirSplit do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:offer_placements, :offer_placements_settlement_conserves)

    create constraint(:offer_placements, :offer_placements_settlement_conserves,
             check: """
               CASE status
               WHEN 'active' THEN ended_at IS NULL AND returned_minor IS NULL AND consumed_minor IS NULL AND forfeited_minor IS NULL
               ELSE ended_at IS NOT NULL
                 AND returned_minor IS NOT NULL AND consumed_minor IS NOT NULL AND forfeited_minor IS NOT NULL
                 AND returned_minor >= 0 AND consumed_minor >= 0 AND forfeited_minor >= 0
                 AND returned_minor + consumed_minor + forfeited_minor = amount_minor
                 AND (status <> 'expired' OR (returned_minor = 0 AND forfeited_minor = 0))
                 AND (status <> 'bought_out' OR forfeited_minor = 0)
                 AND (status <> 'removed_for_policy' OR returned_minor = 0)
             END

             """
           )
  end

  def down do
    drop_if_exists constraint(:offer_placements, :offer_placements_settlement_conserves)

    create constraint(:offer_placements, :offer_placements_settlement_conserves,
             check: """
               CASE status
               WHEN 'active' THEN ended_at IS NULL AND returned_minor IS NULL AND consumed_minor IS NULL AND forfeited_minor IS NULL
               ELSE ended_at IS NOT NULL
                 AND returned_minor >= 0 AND consumed_minor >= 0 AND forfeited_minor >= 0
                 AND returned_minor + consumed_minor + forfeited_minor = amount_minor
                 AND (status <> 'expired' OR (returned_minor = 0 AND forfeited_minor = 0))
                 AND (status <> 'bought_out' OR forfeited_minor = 0)
                 AND (status <> 'removed_for_policy' OR returned_minor = 0)
             END

             """
           )
  end
end
