defmodule Patchbay.Repo.Migrations.AnySiteCheck do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_sites) do
      remove :page_checked_at
      remove :picture_attempts
      remove :picture_tried_at
    end

    create table(:site_checks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :domain, :text, null: false
      add :findings, :map
      add :requested_at, :utc_datetime_usec, null: false
      add :checked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:site_checks, [:domain], name: "site_checks_unique_domain_index")
  end

  def down do
    drop_if_exists unique_index(:site_checks, [:domain], name: "site_checks_unique_domain_index")

    drop table(:site_checks)

    alter table(:forum_sites) do
      add :picture_tried_at, :utc_datetime_usec
      add :picture_attempts, :bigint, null: false, default: 0
      add :page_checked_at, :utc_datetime_usec
    end
  end
end
