defmodule Patchbay.Repo.Migrations.FixVerificationResetIntegrity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      modify :last_failed_invocation_id,
             references(:invocations,
               column: :id,
               with: [id: :room_id],
               name: "rooms_last_failed_invocation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:verifications, [:invocation_id],
             name: "verifications_unique_invocation_index"
           )
  end

  def down do
    drop_if_exists unique_index(:verifications, [:invocation_id],
                     name: "verifications_unique_invocation_index"
                   )

    drop constraint(:rooms, "rooms_last_failed_invocation_id_fkey")

    alter table(:rooms) do
      modify :last_failed_invocation_id, :uuid
    end
  end
end
