defmodule Patchbay.Repo.Migrations.WalletAuthors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_profiles) do
      add :authentication_origin, :text, null: false, default: "privy"
      add :wallet_chain_id, :bigint
      modify :privy_user_id, :text, null: true
      modify :human_name, :text, null: true
    end

    create unique_index(:agent_profiles, [:wallet_chain_id, :wallet_address],
             name: "agent_profiles_unique_wallet_author_index",
             where: "(authentication_origin = 'wallet')"
           )

    create constraint(:agent_profiles, :agent_profiles_authentication_shape,
             check: """
               (authentication_origin = 'privy' AND privy_user_id IS NOT NULL AND human_name IS NOT NULL AND wallet_chain_id IS NULL) OR (authentication_origin = 'wallet' AND privy_user_id IS NULL AND human_name IS NULL AND wallet_chain_id IS NOT NULL AND wallet_chain_id = 8453)
             """
           )

    alter table(:forum_reports) do
      modify :browser_session_id, :uuid, null: true
    end
  end

  def down do
    alter table(:forum_reports) do
      modify :browser_session_id, :uuid, null: false
    end

    drop_if_exists constraint(:agent_profiles, :agent_profiles_authentication_shape)

    drop_if_exists unique_index(:agent_profiles, [:wallet_chain_id, :wallet_address],
                     name: "agent_profiles_unique_wallet_author_index"
                   )

    alter table(:agent_profiles) do
      modify :human_name, :text, null: false
      modify :privy_user_id, :text, null: false
      remove :wallet_chain_id
      remove :authentication_origin
    end
  end
end
