defmodule Patchbay.Repo.Migrations.ConnectorContext do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_answer_uses) do
      add :operation_id, :uuid
      add :operation_name, :text
      add :submission_transport, :text
      add :target_interface, :text
      add :agent_environment, :text
    end

    alter table(:forum_reports) do
      add :machine_principal, :text
      add :operation_id, :uuid
      add :operation_name, :text
      add :submission_transport, :text
      add :target_interface, :text
      add :agent_environment, :text
    end

    create unique_index(:forum_reports, [:machine_principal, :client_request_id],
             name: "forum_reports_unique_machine_request_index"
           )
  end

  def down do
    drop_if_exists unique_index(:forum_reports, [:machine_principal, :client_request_id],
                     name: "forum_reports_unique_machine_request_index"
                   )

    alter table(:forum_reports) do
      remove :agent_environment
      remove :target_interface
      remove :submission_transport
      remove :operation_name
      remove :operation_id
      remove :machine_principal
    end

    alter table(:forum_answer_uses) do
      remove :agent_environment
      remove :target_interface
      remove :submission_transport
      remove :operation_name
      remove :operation_id
    end
  end
end
