defmodule Patchbay.Repo.Migrations.PersistRoomInvocationEpochs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:invocations) do
      add :invocation_epoch, :bigint, null: false, default: 0
    end

    alter table(:rooms) do
      add :invocation_epoch, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:rooms) do
      remove :invocation_epoch
    end

    alter table(:invocations) do
      remove :invocation_epoch
    end
  end
end
