defmodule Patchbay.Repo.Migrations.AddOneOpenAssistRunPerPayer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:assist_runs, [:payer_profile_id],
             name: "assist_runs_one_open_run_per_payer_index",
             where: "(status IN ('paid', 'running'))"
           )
  end

  def down do
    drop_if_exists unique_index(:assist_runs, [:payer_profile_id],
                     name: "assist_runs_one_open_run_per_payer_index"
                   )
  end
end
