defmodule Patchbay.Repo.Migrations.OfferReportDecisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:offer_moderation_actions) do
      add :report_id,
          references(:offer_reports,
            column: :id,
            name: "offer_moderation_actions_report_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create index(:offer_moderation_actions, [:report_id])
  end

  def down do
    drop_if_exists index(:offer_moderation_actions, [:report_id])

    drop constraint(:offer_moderation_actions, "offer_moderation_actions_report_id_fkey")

    alter table(:offer_moderation_actions) do
      remove :report_id
    end
  end
end
