defmodule Patchbay.Repo.Migrations.PairedAssistAccess do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:assist_runs) do
      add :acting_agent_id, :uuid
      add :beneficiary_profile_id, :uuid
      add :human_account_id, :bigint
      add :pairing_id, :uuid
    end
  end

  def down do
    alter table(:assist_runs) do
      remove :pairing_id
      remove :human_account_id
      remove :beneficiary_profile_id
      remove :acting_agent_id
    end
  end
end
