defmodule Patchbay.Patchbay.Types.FailureCode do
  use Ash.Type.Enum,
    values: [
      :VISIBLE_POSTCONDITION_NOT_MET,
      :SOURCE_CHANGED_DURING_INVOCATION,
      :CANDIDATE_EMPTY,
      :CANDIDATE_DIGEST_MISMATCH,
      :FRONTMATTER_INVALID,
      :IDENTITY_NOT_PRESERVED,
      :STALE_TOOL_REVISION,
      :STALE_BROWSER_SESSION,
      :UI_REVISION_NOT_APPLIED,
      :MODEL_GENERATION_FAILED,
      :EXECUTION_CANCELLED
    ]
end
