defmodule Patchbay.Repo.Migrations.AddPaymentIntents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:payment_intents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :payment_identifier, :text, null: false
      add :kind, :text, null: false
      add :actor_profile_id, :uuid, null: false
      add :target_type, :text, null: false
      add :target_id, :uuid, null: false
      add :amount_atomic, :bigint, null: false
      add :asset, :text, null: false
      add :network, :text, null: false
      add :payload, :map, null: false
      add :payload_digest, :text, null: false
      add :recipient_snapshot, {:array, :map}, null: false
      add :effect_summary, :text, null: false
      add :status, :text, null: false, default: "prepared"
      add :expires_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:payment_intents, [:payment_identifier],
             name: "payment_intents_unique_payment_identifier_index"
           )

    create table(:payment_receipts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :payment_identifier, :text, null: false
      add :payer_address, :text, null: false
      add :network, :text, null: false
      add :asset, :text, null: false
      add :amount_atomic, :bigint, null: false
      add :facilitator, :text, null: false
      add :transaction_hash, :text
      add :payment_response, :map, null: false
      add :settled_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :payment_intent_id,
          references(:payment_intents,
            column: :id,
            name: "payment_receipts_payment_intent_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:payment_receipts, [:payment_identifier],
             name: "payment_receipts_unique_payment_identifier_index"
           )

    create unique_index(:payment_receipts, [:transaction_hash],
             name: "payment_receipts_unique_transaction_hash_index"
           )
  end

  def down do
    drop constraint(:payment_receipts, "payment_receipts_payment_intent_id_fkey")

    drop_if_exists unique_index(:payment_receipts, [:transaction_hash],
                     name: "payment_receipts_unique_transaction_hash_index"
                   )

    drop_if_exists unique_index(:payment_receipts, [:payment_identifier],
                     name: "payment_receipts_unique_payment_identifier_index"
                   )

    drop table(:payment_receipts)

    drop_if_exists unique_index(:payment_intents, [:payment_identifier],
                     name: "payment_intents_unique_payment_identifier_index"
                   )

    drop table(:payment_intents)
  end
end
