defmodule Patchbay.Repo.Migrations.CascadeRoomDeletes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:browser_sessions, "browser_sessions_room_id_fkey")

    alter table(:browser_sessions) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "browser_sessions_room_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:invocations, "invocations_room_id_fkey")

    alter table(:invocations) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "invocations_room_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:invocations, "invocations_browser_session_id_fkey")

    alter table(:invocations) do
      modify :browser_session_id,
             references(:browser_sessions,
               column: :id,
               with: [room_id: :room_id],
               name: "invocations_browser_session_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:invocations, "invocations_tool_revision_id_fkey")

    alter table(:invocations) do
      modify :tool_revision_id,
             references(:tool_revisions,
               column: :id,
               with: [room_id: :room_id],
               name: "invocations_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:repair_proposals, "repair_proposals_candidate_tool_revision_id_fkey")

    alter table(:repair_proposals) do
      modify :candidate_tool_revision_id,
             references(:tool_revisions,
               column: :id,
               with: [room_id: :room_id],
               name: "repair_proposals_candidate_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:repair_proposals, "repair_proposals_room_id_fkey")

    alter table(:repair_proposals) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "repair_proposals_room_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:repair_proposals, "repair_proposals_source_invocation_id_fkey")

    alter table(:repair_proposals) do
      modify :source_invocation_id,
             references(:invocations,
               column: :id,
               with: [room_id: :room_id],
               name: "repair_proposals_source_invocation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:repair_proposals, "repair_proposals_source_tool_revision_id_fkey")

    alter table(:repair_proposals) do
      modify :source_tool_revision_id,
             references(:tool_revisions,
               column: :id,
               with: [room_id: :room_id],
               name: "repair_proposals_source_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:room_events, "room_events_room_id_fkey")

    alter table(:room_events) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "room_events_room_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:room_events, "room_events_browser_session_id_fkey")

    alter table(:room_events) do
      modify :browser_session_id,
             references(:browser_sessions,
               column: :id,
               with: [room_id: :room_id],
               name: "room_events_browser_session_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:tool_revisions, "tool_revisions_parent_revision_id_fkey")

    alter table(:tool_revisions) do
      modify :parent_revision_id,
             references(:tool_revisions,
               column: :id,
               with: [room_id: :room_id],
               name: "tool_revisions_parent_revision_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:tool_revisions, "tool_revisions_room_id_fkey")

    alter table(:tool_revisions) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "tool_revisions_room_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:verifications, "verifications_room_id_fkey")

    alter table(:verifications) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "verifications_room_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:verifications, "verifications_invocation_id_fkey")

    alter table(:verifications) do
      modify :invocation_id,
             references(:invocations,
               column: :id,
               with: [room_id: :room_id],
               name: "verifications_invocation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:verifications, "verifications_invocation_id_fkey")

    drop constraint(:verifications, "verifications_room_id_fkey")

    alter table(:verifications) do
      modify :invocation_id,
             references(:invocations,
               column: :id,
               with: [room_id: :room_id],
               name: "verifications_invocation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:verifications) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "verifications_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:tool_revisions, "tool_revisions_room_id_fkey")

    drop constraint(:tool_revisions, "tool_revisions_parent_revision_id_fkey")

    alter table(:tool_revisions) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "tool_revisions_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tool_revisions) do
      modify :parent_revision_id,
             references(:tool_revisions,
               column: :id,
               with: [room_id: :room_id],
               name: "tool_revisions_parent_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:room_events, "room_events_browser_session_id_fkey")

    drop constraint(:room_events, "room_events_room_id_fkey")

    alter table(:room_events) do
      modify :browser_session_id,
             references(:browser_sessions,
               column: :id,
               with: [room_id: :room_id],
               name: "room_events_browser_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:room_events) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "room_events_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:repair_proposals, "repair_proposals_source_tool_revision_id_fkey")

    drop constraint(:repair_proposals, "repair_proposals_source_invocation_id_fkey")

    drop constraint(:repair_proposals, "repair_proposals_room_id_fkey")

    drop constraint(:repair_proposals, "repair_proposals_candidate_tool_revision_id_fkey")

    alter table(:repair_proposals) do
      modify :source_tool_revision_id,
             references(:tool_revisions,
               column: :id,
               with: [room_id: :room_id],
               name: "repair_proposals_source_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:repair_proposals) do
      modify :source_invocation_id,
             references(:invocations,
               column: :id,
               with: [room_id: :room_id],
               name: "repair_proposals_source_invocation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:repair_proposals) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "repair_proposals_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:repair_proposals) do
      modify :candidate_tool_revision_id,
             references(:tool_revisions,
               column: :id,
               with: [room_id: :room_id],
               name: "repair_proposals_candidate_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:invocations, "invocations_tool_revision_id_fkey")

    drop constraint(:invocations, "invocations_browser_session_id_fkey")

    drop constraint(:invocations, "invocations_room_id_fkey")

    alter table(:invocations) do
      modify :tool_revision_id,
             references(:tool_revisions,
               column: :id,
               with: [room_id: :room_id],
               name: "invocations_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:invocations) do
      modify :browser_session_id,
             references(:browser_sessions,
               column: :id,
               with: [room_id: :room_id],
               name: "invocations_browser_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:invocations) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "invocations_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:browser_sessions, "browser_sessions_room_id_fkey")

    alter table(:browser_sessions) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "browser_sessions_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
