defmodule Patchbay.Repo.Migrations.DirectoryCatalog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_sites) do
      add :slug, :text
      add :display_name, :text
      add :entity_type, :text
      add :organization_name, :text
      add :canonical_domain, :text
      add :support_relationship, :text
      add :support_status, :text
      add :support_evidence_url, :text
      add :support_evidence_label, :text
      add :last_verified_at, :utc_datetime_usec
      add :tool_inventory_status, :text
      add :logo_path, :text
      add :logo_source_url, :text
      add :logo_usage_note, :text
      add :screenshot_path, :text
      add :screenshot_source_url, :text
      add :screenshot_captured_at, :utc_datetime_usec
      add :featured_rank, :bigint
    end

    create unique_index(:forum_sites, [:slug], name: "forum_sites_unique_slug_index")

    alter table(:forum_tools) do
      add :stable_key, :text
      add :published_name, :text
      add :display_name, :text
      add :protocol_version, :text
      add :input_schema, :map
      add :output_schema, :map
      add :raw_definition, :map
      add :source_kind, :text, null: false, default: "observed"
      add :source_url, :text
      add :status, :text, null: false, default: "active"
    end
  end

  def down do
    alter table(:forum_tools) do
      remove :status
      remove :source_url
      remove :source_kind
      remove :raw_definition
      remove :output_schema
      remove :input_schema
      remove :protocol_version
      remove :display_name
      remove :published_name
      remove :stable_key
    end

    drop_if_exists unique_index(:forum_sites, [:slug], name: "forum_sites_unique_slug_index")

    alter table(:forum_sites) do
      remove :featured_rank
      remove :screenshot_captured_at
      remove :screenshot_source_url
      remove :screenshot_path
      remove :logo_usage_note
      remove :logo_source_url
      remove :logo_path
      remove :tool_inventory_status
      remove :last_verified_at
      remove :support_evidence_label
      remove :support_evidence_url
      remove :support_status
      remove :support_relationship
      remove :canonical_domain
      remove :organization_name
      remove :entity_type
      remove :display_name
      remove :slug
    end
  end
end
