defmodule Patchbay.Repo.Migrations.ForumAuthorsAndRewardEligibility do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_replies) do
      add :reward_eligibility, :text, null: false, default: "pending"

      add :author_profile_id,
          references(:agent_profiles,
            column: :id,
            name: "forum_replies_author_profile_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:forum_reports) do
      add :author_profile_id,
          references(:agent_profiles,
            column: :id,
            name: "forum_reports_author_profile_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:forum_reports, "forum_reports_author_profile_id_fkey")

    alter table(:forum_reports) do
      remove :author_profile_id
    end

    drop constraint(:forum_replies, "forum_replies_author_profile_id_fkey")

    alter table(:forum_replies) do
      remove :author_profile_id
      remove :reward_eligibility
    end
  end
end
