defmodule Patchbay.Repo.Migrations.FixPatchbayRelationalIntegrity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:browser_sessions, [:id, :room_id],
             name: "browser_sessions_unique_id_per_room_index"
           )

    drop constraint(:invocations, "invocations_browser_session_id_fkey")

    create unique_index(:invocations, [:id, :room_id],
             name: "invocations_unique_id_per_room_index"
           )

    alter table(:invocations) do
      modify :browser_session_id,
             references(:browser_sessions,
               column: :id,
               with: [room_id: :room_id],
               name: "invocations_browser_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:invocations, "invocations_tool_revision_id_fkey")

    drop constraint(:repair_proposals, "repair_proposals_candidate_tool_revision_id_fkey")

    drop constraint(:repair_proposals, "repair_proposals_source_invocation_id_fkey")

    alter table(:repair_proposals) do
      modify :source_invocation_id,
             references(:invocations,
               column: :id,
               with: [room_id: :room_id],
               name: "repair_proposals_source_invocation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:repair_proposals, "repair_proposals_source_tool_revision_id_fkey")

    drop constraint(:room_events, "room_events_browser_session_id_fkey")

    alter table(:room_events) do
      modify :browser_session_id,
             references(:browser_sessions,
               column: :id,
               with: [room_id: :room_id],
               name: "room_events_browser_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:tool_revisions, "tool_revisions_parent_revision_id_fkey")

    create unique_index(:tool_revisions, [:id, :room_id],
             name: "tool_revisions_unique_id_per_room_index"
           )

    alter table(:invocations) do
      modify :tool_revision_id,
             references(:tool_revisions,
               column: :id,
               with: [room_id: :room_id],
               name: "invocations_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:repair_proposals) do
      modify :candidate_tool_revision_id,
             references(:tool_revisions,
               column: :id,
               with: [room_id: :room_id],
               name: "repair_proposals_candidate_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :source_tool_revision_id,
             references(:tool_revisions,
               column: :id,
               with: [room_id: :room_id],
               name: "repair_proposals_source_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tool_revisions) do
      modify :parent_revision_id,
             references(:tool_revisions,
               column: :id,
               with: [room_id: :room_id],
               name: "tool_revisions_parent_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:verifications, "verifications_invocation_id_fkey")

    alter table(:verifications) do
      modify :invocation_id,
             references(:invocations,
               column: :id,
               with: [room_id: :room_id],
               name: "verifications_invocation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:verifications, "verifications_invocation_id_fkey")

    alter table(:verifications) do
      modify :invocation_id,
             references(:invocations,
               column: :id,
               name: "verifications_invocation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:tool_revisions, "tool_revisions_parent_revision_id_fkey")

    alter table(:tool_revisions) do
      modify :parent_revision_id,
             references(:tool_revisions,
               column: :id,
               name: "tool_revisions_parent_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:repair_proposals, "repair_proposals_source_tool_revision_id_fkey")

    drop constraint(:repair_proposals, "repair_proposals_source_invocation_id_fkey")

    drop constraint(:repair_proposals, "repair_proposals_candidate_tool_revision_id_fkey")

    alter table(:repair_proposals) do
      modify :source_tool_revision_id,
             references(:tool_revisions,
               column: :id,
               name: "repair_proposals_source_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :candidate_tool_revision_id,
             references(:tool_revisions,
               column: :id,
               name: "repair_proposals_candidate_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:invocations, "invocations_tool_revision_id_fkey")

    drop constraint(:invocations, "invocations_browser_session_id_fkey")

    alter table(:invocations) do
      modify :tool_revision_id,
             references(:tool_revisions,
               column: :id,
               name: "invocations_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:tool_revisions, [:id, :room_id],
                     name: "tool_revisions_unique_id_per_room_index"
                   )

    drop constraint(:room_events, "room_events_browser_session_id_fkey")

    alter table(:room_events) do
      modify :browser_session_id,
             references(:browser_sessions,
               column: :id,
               name: "room_events_browser_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:repair_proposals) do
      modify :source_invocation_id,
             references(:invocations,
               column: :id,
               name: "repair_proposals_source_invocation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:invocations) do
      modify :browser_session_id,
             references(:browser_sessions,
               column: :id,
               name: "invocations_browser_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:invocations, [:id, :room_id],
                     name: "invocations_unique_id_per_room_index"
                   )

    drop_if_exists unique_index(:browser_sessions, [:id, :room_id],
                     name: "browser_sessions_unique_id_per_room_index"
                   )
  end
end
