defmodule Patchbay.Repo.Migrations.AllowReusedGenerationAfterReset do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:tool_revisions, [:room_id, :generation],
                     name: "tool_revisions_unique_generation_per_room_index"
                   )

    create unique_index(:tool_revisions, [:room_id, :generation],
             name: "tool_revisions_unique_active_generation_per_room_index",
             where: "(status <> 'retired')"
           )
  end

  def down do
    raise "irreversible: reset reruns may create multiple retired revisions for one generation"
  end
end
