defmodule Patchbay.Repo.Migrations.BootstrapPatchbay do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:browser_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :client_instance_id, :uuid, null: false
      add :user_agent_digest, :text, null: false
      add :webmcp_supported, :boolean, null: false, default: false
      add :desired_generation, :bigint, null: false, default: 1
      add :observed_generation, :bigint
      add :observed_tool_names, {:array, :text}, null: false, default: []
      add :observed_contracts, :map, null: false, default: %{}
      add :toolchange_count, :bigint, null: false, default: 0

      add :connected_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :last_seen_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :disconnected_at, :utc_datetime_usec
      add :room_id, :uuid, null: false
    end

    create unique_index(:browser_sessions, [:client_instance_id],
             name: "browser_sessions_unique_client_instance_id_index"
           )

    create table(:invocations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :request_uuid, :uuid, null: false
      add :tool_contract_sha256, :text, null: false
      add :arguments, :map, null: false, default: %{}
      add :arguments_sha256, :text, null: false
      add :pre_state, :map, null: false, default: %{}
      add :handler_result, :map, null: false, default: %{}
      add :handler_reported_success, :boolean, null: false, default: false
      add :generated_candidate, :text
      add :generated_candidate_sha256, :text
      add :generation_key, :text
      add :post_state, :map, null: false, default: %{}
      add :effective_status, :text, null: false, default: "started"
      add :failure_code, :text
      add :duration_ms, :bigint

      add :started_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :handler_returned_at, :utc_datetime_usec
      add :verified_at, :utc_datetime_usec
      add :room_id, :uuid, null: false
    end

    create unique_index(:invocations, [:request_uuid],
             name: "invocations_unique_request_uuid_index"
           )

    alter table(:invocations) do
      add :browser_session_id,
          references(:browser_sessions,
            column: :id,
            name: "invocations_browser_session_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :tool_revision_id, :uuid, null: false
    end

    create table(:repair_proposals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :candidate_tool_revision_id, :uuid
      add :status, :text, null: false, default: "requested"
      add :root_cause, :text, null: false
      add :repair_plan, :map, null: false, default: %{}
      add :contract_diff, :map, null: false, default: %{}
      add :canary_result, :map, null: false, default: %{}
      add :risk_notes, {:array, :text}, null: false, default: []
      add :model, :text, null: false
      add :model_response_id, :text, null: false
      add :prompt_version, :text, null: false
      add :input_sha256, :text, null: false
      add :approved_by, :text
      add :approved_at, :utc_datetime_usec
      add :rejected_at, :utc_datetime_usec
      add :published_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id, :uuid, null: false

      add :source_invocation_id,
          references(:invocations,
            column: :id,
            name: "repair_proposals_source_invocation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :source_tool_revision_id, :uuid, null: false
    end

    create table(:room_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sequence, :bigint, null: false
      add :kind, :text, null: false
      add :payload, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id, :uuid, null: false
    end

    create unique_index(:room_events, [:room_id, :sequence],
             name: "room_events_unique_sequence_per_room_index"
           )

    alter table(:room_events) do
      add :browser_session_id,
          references(:browser_sessions,
            column: :id,
            name: "room_events_browser_session_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:rooms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:browser_sessions) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "browser_sessions_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:invocations) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "invocations_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:repair_proposals) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "repair_proposals_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:room_events) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "room_events_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:rooms) do
      add :slug, :text, null: false
      add :title, :text, null: false
      add :status, :text, null: false, default: "ready"
      add :goal_kind, :text, null: false, default: "skill_uplift"
      add :goal_text, :text, null: false
      add :source_markdown, :text, null: false
      add :source_sha256, :text, null: false
      add :candidate_markdown, :text
      add :candidate_sha256, :text
      add :ui_revision, :bigint, null: false, default: 0
      add :desired_tool_generation, :bigint, null: false, default: 1
      add :seed_version, :text, null: false
      add :last_failed_invocation_id, :uuid
      add :active_repair_proposal_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:rooms, [:slug], name: "rooms_unique_slug_index")

    create table(:tool_revisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:invocations) do
      modify :tool_revision_id,
             references(:tool_revisions,
               column: :id,
               name: "invocations_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:repair_proposals) do
      modify :candidate_tool_revision_id,
             references(:tool_revisions,
               column: :id,
               name: "repair_proposals_candidate_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :source_tool_revision_id,
             references(:tool_revisions,
               column: :id,
               name: "repair_proposals_source_tool_revision_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tool_revisions) do
      add :parent_revision_id,
          references(:tool_revisions,
            column: :id,
            name: "tool_revisions_parent_revision_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :generation, :bigint, null: false
      add :name, :text, null: false
      add :title, :text, null: false
      add :description, :text, null: false
      add :input_schema, :map, null: false, default: %{}
      add :annotations, :map, null: false, default: %{}
      add :handler_adapter, :text, null: false
      add :output_contract, :map, null: false, default: %{}
      add :postcondition_set, :text, null: false
      add :contract_sha256, :text, null: false
      add :origin, :text, null: false, default: "seed"
      add :status, :text, null: false, default: "candidate"
      add :published_at, :utc_datetime_usec
      add :retired_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id,
          references(:rooms,
            column: :id,
            name: "tool_revisions_room_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:tool_revisions, [:room_id, :generation],
             name: "tool_revisions_unique_generation_per_room_index"
           )

    create unique_index(:tool_revisions, [:room_id],
             name: "tool_revisions_unique_desired_revision_per_room_index",
             where: "(status = 'desired')"
           )

    create table(:verifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :goal_kind, :text, null: false, default: "skill_uplift"
      add :checks, :map, null: false, default: %{}
      add :passed, :boolean, null: false, default: false
      add :failure_code, :text
      add :expected_state, :map, null: false, default: %{}
      add :observed_state, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id,
          references(:rooms,
            column: :id,
            name: "verifications_room_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :invocation_id,
          references(:invocations,
            column: :id,
            name: "verifications_invocation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:verifications, "verifications_invocation_id_fkey")

    drop constraint(:verifications, "verifications_room_id_fkey")

    drop table(:verifications)

    drop constraint(:tool_revisions, "tool_revisions_room_id_fkey")

    drop constraint(:tool_revisions, "tool_revisions_parent_revision_id_fkey")

    drop_if_exists unique_index(:tool_revisions, [:room_id],
                     name: "tool_revisions_unique_desired_revision_per_room_index"
                   )

    drop_if_exists unique_index(:tool_revisions, [:room_id, :generation],
                     name: "tool_revisions_unique_generation_per_room_index"
                   )

    alter table(:tool_revisions) do
      remove :room_id
      remove :inserted_at
      remove :retired_at
      remove :published_at
      remove :status
      remove :origin
      remove :contract_sha256
      remove :postcondition_set
      remove :output_contract
      remove :handler_adapter
      remove :annotations
      remove :input_schema
      remove :description
      remove :title
      remove :name
      remove :generation
      remove :parent_revision_id
    end

    drop constraint(:repair_proposals, "repair_proposals_source_tool_revision_id_fkey")

    drop constraint(:repair_proposals, "repair_proposals_source_invocation_id_fkey")

    drop constraint(:repair_proposals, "repair_proposals_room_id_fkey")

    drop constraint(:repair_proposals, "repair_proposals_candidate_tool_revision_id_fkey")

    alter table(:repair_proposals) do
      modify :source_tool_revision_id, :uuid
      modify :candidate_tool_revision_id, :uuid
    end

    drop constraint(:invocations, "invocations_tool_revision_id_fkey")

    drop constraint(:invocations, "invocations_browser_session_id_fkey")

    drop constraint(:invocations, "invocations_room_id_fkey")

    alter table(:invocations) do
      modify :tool_revision_id, :uuid
    end

    drop table(:tool_revisions)

    drop_if_exists unique_index(:rooms, [:slug], name: "rooms_unique_slug_index")

    alter table(:rooms) do
      remove :updated_at
      remove :inserted_at
      remove :active_repair_proposal_id
      remove :last_failed_invocation_id
      remove :seed_version
      remove :desired_tool_generation
      remove :ui_revision
      remove :candidate_sha256
      remove :candidate_markdown
      remove :source_sha256
      remove :source_markdown
      remove :goal_text
      remove :goal_kind
      remove :status
      remove :title
      remove :slug
    end

    drop constraint(:room_events, "room_events_browser_session_id_fkey")

    drop constraint(:room_events, "room_events_room_id_fkey")

    alter table(:room_events) do
      modify :room_id, :uuid
    end

    alter table(:repair_proposals) do
      modify :room_id, :uuid
    end

    alter table(:invocations) do
      modify :room_id, :uuid
    end

    drop constraint(:browser_sessions, "browser_sessions_room_id_fkey")

    alter table(:browser_sessions) do
      modify :room_id, :uuid
    end

    drop table(:rooms)

    alter table(:room_events) do
      remove :browser_session_id
    end

    drop_if_exists unique_index(:room_events, [:room_id, :sequence],
                     name: "room_events_unique_sequence_per_room_index"
                   )

    drop table(:room_events)

    drop table(:repair_proposals)

    alter table(:invocations) do
      remove :tool_revision_id
      remove :browser_session_id
    end

    drop_if_exists unique_index(:invocations, [:request_uuid],
                     name: "invocations_unique_request_uuid_index"
                   )

    drop table(:invocations)

    drop_if_exists unique_index(:browser_sessions, [:client_instance_id],
                     name: "browser_sessions_unique_client_instance_id_index"
                   )

    drop table(:browser_sessions)
  end
end
