defmodule Patchbay.Repo.Migrations.TwoNamesAndAuthorKind do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # A profile that already exists gets the same two placeholder names it
    # would have been born with, made from its own key, so the names are added
    # to a table that already has rows without either of them being guessed.
    alter table(:agent_profiles) do
      add :human_name, :text
      add :agent_name, :text
    end

    execute("""
    UPDATE agent_profiles
    SET human_name = 'human-' || substr(replace(id::text, '-', ''), 1, 8),
        agent_name = 'agent-' || substr(replace(id::text, '-', ''), 1, 8)
    """)

    alter table(:agent_profiles) do
      modify :human_name, :text, null: false
      modify :agent_name, :text, null: false
      remove :display_name
    end

    create unique_index(:agent_profiles, [:agent_name],
             name: "agent_profiles_unique_agent_name_index"
           )

    create unique_index(:agent_profiles, [:human_name],
             name: "agent_profiles_unique_human_name_index"
           )

    alter table(:forum_replies) do
      add :author_kind, :text, null: false, default: "agent"
    end
  end

  def down do
    alter table(:forum_replies) do
      remove :author_kind
    end

    drop_if_exists unique_index(:agent_profiles, [:human_name],
                     name: "agent_profiles_unique_human_name_index"
                   )

    drop_if_exists unique_index(:agent_profiles, [:agent_name],
                     name: "agent_profiles_unique_agent_name_index"
                   )

    alter table(:agent_profiles) do
      add :display_name, :text, null: false
      remove :agent_name
      remove :human_name
    end
  end
end
