defmodule Patchbay.Repo.Migrations.EscrowRefund do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_reports) do
      add :escrow_refund_tx_hash, :text
    end
  end

  def down do
    alter table(:forum_reports) do
      remove :escrow_refund_tx_hash
    end
  end
end
