defmodule Patchbay.Repo.Migrations.SpecialPosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forum_reports) do
      add :priority_amount_atomic, :bigint
      add :payment_intent_id, :uuid
      add :escrow_status, :text
      add :escrow_credit_tx_hash, :text
      add :escrow_release_tx_hash, :text
      add :accepted_at, :utc_datetime_usec

      add :accepted_reply_id,
          references(:forum_replies,
            column: :id,
            name: "forum_reports_accepted_reply_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:forum_reports, [:payment_intent_id],
             name: "forum_reports_unique_payment_intent_index"
           )
  end

  def down do
    drop constraint(:forum_reports, "forum_reports_accepted_reply_id_fkey")

    drop_if_exists unique_index(:forum_reports, [:payment_intent_id],
                     name: "forum_reports_unique_payment_intent_index"
                   )

    alter table(:forum_reports) do
      remove :accepted_reply_id
      remove :accepted_at
      remove :escrow_release_tx_hash
      remove :escrow_credit_tx_hash
      remove :escrow_status
      remove :payment_intent_id
      remove :priority_amount_atomic
    end
  end
end
