defmodule PatchbayWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :patchbay

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_patchbay_key",
    signing_salt: "8IPnb8sh",
    same_site: "Lax",
    max_age: Application.compile_env!(:patchbay, :sign_in_lifetime_seconds)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  plug PatchbayWeb.Plugs.CanonicalHost

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :patchbay,
    gzip: not code_reloading?,
    only: PatchbayWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Everything else, error pages included, is served under the strict policy
  # unless its pipeline sets another.
  plug :put_reading_policy

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :patchbay
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Before the body is parsed, so a body that cannot be read is refused in
  # the format chosen for its path: JSON under these prefixes, otherwise
  # whatever the caller's Accept header prefers.
  plug RegentAgentAccess.Plug,
    documents: &PatchbayWeb.PublicDocuments.document/1,
    guide: "/llms.txt",
    json_prefixes: ~w(api forum hello mcp)

  plug PatchbayWeb.Plugs.Parsers,
    body_reader: {PatchbayWeb.WalletBodyReader, :read_body, []},
    # A forum post from the home page carries up to three 3 MB pictures.
    parsers: [:urlencoded, {:multipart, length: 10_000_000}, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PatchbayWeb.Plugs.ReadBudget
  plug PatchbayWeb.Router

  defp put_reading_policy(conn, _opts) do
    put_resp_header(conn, "content-security-policy", PatchbayWeb.ContentSecurityPolicy.reading())
  end
end
